### ISSUE TITLE
Creation of android project 

### ISSUE THREAD

**Issue by sanidhyakr18** [unnati914/Care4ther-#12]
I would like to create a new android project and add it to this repo.
For now, it will be just a basic hello world project so that we can get started with android part of this project.

Kindly assign this issue to me.
Thank you.

**Comment by sanidhyakr18** [comment]
Thanks, @unnati914  for assigning me this issue.

I need your approval for a few things like the app's name, package name, language and the min SDK.

Here's what I had in mind:
Name - Care4ther
Package Name - com.crosswoc.care4ther
Language - Kotlin (Since most of the developers now prefer Kotlin over Java)
Min SDK - API 23: Android 6.0 (Marshmallow)

Let me know if this sounds good, or do you want to suggest any changes?

**Comment by unnati914** [comment]
You could work on kotlin no issues :)
Do let me know if you need any help :)
