### ISSUE TITLE
add banner of crosswoc to the readme file

### ISSUE THREAD

**Issue by kmryashasvi** [unnati914/Care4ther-#26]
I will add banner of crosswoc to the readme file so that, People will know it is associated to crosswoc. Moreover, I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by kmryashasvi** [comment]
Hello,
When will you add the label of crosswoc and difficulty label?

**Comment by kmryashasvi** [comment]
I have done the required changes,
why aren't you merging it

**Comment by unnati914** [comment]
I'm busy with my papers will do it by today

**Comment by kmryashasvi** [comment]
That today ended 3 days ago,
When are your exams ending?

**Comment by unnati914** [comment]
I am sorry i will merge it today
