### ISSUE TITLE
Remove space from repo name

### ISSUE THREAD

**Issue by aryasoni98** [unnati914/Care4ther-#40]
**Describe the bug**
----
Before : unnati914/Care4ther-
After : unnati914/Care4ther ( Remove Space )

**To Reproduce**
----
- Steps to reproduce the behaviour:
  4. See an error

**Expected behaviour**
-----
- A clear and concise description of what you expected to happen.

**Possible solution**
----
- Describe the solution you thought of.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

![Screenshot 2021-08-24 at 9 29 44 PM](https://user-images.githubusercontent.com/18515597/130650267-09a486a3-6f1c-4db8-97d8-4fa3153c1c42.png)

**Additional context**
----
- Add any other context about the problem here. You can also mention the system environment in which you are running it.

**Comment by unnati914** [comment]
sure
