### ISSUE TITLE
Update The Readme

### ISSUE THREAD

**Issue by unnati914** [unnati914/Care4ther-#5]
You have To update the readme whatever feature u added in the project.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by unnati914** [comment]
> Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

Sure I will be making a contributors.md file make sure you write your name there

**Comment by Akash20x** [comment]
I withdraw from issue

**Comment by aryasoni98** [comment]
Could I work on this?
